[options]
admin_passwd = e2e-local-admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons,/mnt/enterprise,/usr/lib/python3/dist-packages/odoo/addons
without_demo = all
proxy_mode = False
list_db = False
workers = 0
max_cron_threads = 1
limit_time_cpu = 120
limit_time_real = 240
